S4_Exploratory Data Analysis Using Python

In [1]:
import numpy as np
total_amounts= np.array([2188,636,3399,3126,3132,380,2581,3239,3259,3088])
print(total_amounts.shape)
print(total_amounts.dtype)

(10,)
int64


In [2]:
#use slicing(with condition) to get orders with total amount of each order
high_value_orders = total_amounts[total_amounts > 3250]
print(high_value_orders)

[3399 3259]


In [3]:
total_amounts > 3250

array([False, False,  True, False, False, False, False, False,  True,
       False])

In [4]:
order_amount_2=total_amounts[1]
print(order_amount_2)

636


In [5]:
last_order_amount=total_amounts[-1]
print(last_order_amount)

3088


In [6]:
#Add another amount($3033) of the next order
total_amounts = np.append(total_amounts,3033)
print(total_amounts)

[2188  636 3399 3126 3132  380 2581 3239 3259 3088 3033]


In [7]:
# Update total amount above 3250
updated_amounts = np.where(total_amounts > 3250,
                           total_amounts*(1-10/100),
                           total_amounts)
print(updated_amounts)

[2188.   636.  3059.1 3126.  3132.   380.  2581.  3239.  2933.1 3088.
 3033. ]


In [8]:
import pandas as pd
Orders = pd.read_csv("/content/DA314_S1_Orders_Data_Concept.csv")
Orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1967 entries, 0 to 1966
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   order_id        1967 non-null   object
 1   user_id         1967 non-null   object
 2   restaurant_id   1967 non-null   object
 3   order_date      1967 non-null   object
 4   total_amount    1967 non-null   int64 
 5   items_ordered   1967 non-null   object
 6   payment_method  1967 non-null   object
 7   order_status    1967 non-null   object
dtypes: int64(1), object(7)
memory usage: 123.1+ KB


In [9]:
#Access columns
total_amount = Orders['total_amount']  #single sqrt [] is a series
print(total_amount)

0       2188
1        636
2       3399
3       3126
4       3123
        ... 
1962    3219
1963    1919
1964    1998
1965    1786
1966    2955
Name: total_amount, Length: 1967, dtype: int64


In [10]:
#Access rows
order_4 = Orders.loc[3]
print(order_4)

order_id                             ORD0004
user_id                               USR098
restaurant_id                         RST013
order_date                        01/04/2024
total_amount                            3126
items_ordered     Butter Naan, Chicken Curry
payment_method                        Wallet
order_status                       Cancelled
Name: 3, dtype: object


In [11]:
#Summarize data
avg_amount = np.round(Orders['total_amount'].mean(),2)
print(avg_amount)

1935.85


In [12]:
# Update  a row
Orders.loc[Orders['order_id'] == 'ORD0004', ['total_amount','payment_method']] = [1300,'UPI']
order_4_updated = Orders[Orders['order_id'] == 'ORD0004']
print(order_4_updated)

  order_id user_id restaurant_id  order_date  total_amount  \
3  ORD0004  USR098        RST013  01/04/2024          1300   

                items_ordered payment_method order_status  
3  Butter Naan, Chicken Curry            UPI    Cancelled  


In [13]:
order_4_updated

order_id user_id restaurant_id  order_date  total_amount  \
3  ORD0004  USR098        RST013  01/04/2024          1300   

                items_ordered payment_method order_status  
3  Butter Naan, Chicken Curry            UPI    Cancelled

In [14]:
Orders[['total_amount','payment_method','order_status']]   #double s1qrt[] are DataFrame

total_amount payment_method order_status
0             2188    Credit Card    Completed
1              636            UPI    Completed
2             3399           Cash    Completed
3             1300            UPI    Cancelled
4             3123         Wallet    Cancelled
...            ...            ...          ...
1962          3219         Wallet    Cancelled
1963          1919            UPI    Completed
1964          1998         Wallet    Completed
1965          1786           Cash    Completed
1966          2955           Cash    Completed

[1967 rows x 3 columns]

Reading the data file in numpy

In [18]:
import numpy as np
orders_data = np.genfromtxt('/content/DA314_S1_Orders20_Data_Concept.csv',
                           delimiter=',',
                           skip_header=1,
                           usecols=(0,1,2),
                           max_rows=10
                           )
orders_data=orders_data.astype(int)
print(orders_data[:5])  #shows first 5 rows

[[   1    7 2188]
 [   2   44  636]
 [   3   58 3399]
 [   4   13 3126]
 [   5   30 3123]]


In [19]:
orders_data

array([[   1,    7, 2188],
       [   2,   44,  636],
       [   3,   58, 3399],
       [   4,   13, 3126],
       [   5,   30, 3123],
       [   6,   34,  380],
       [   7,    9, 2581],
       [   8,   13, 3239],
       [   9,   77, 3259],
       [  10,   13, 3088]])

In [20]:
print("Third Order:",orders_data[2])

Third Order: [   3   58 3399]


In [22]:
amounts=orders_data[:,2]   #Acessing 'total_amount' column(index 2)
print(amounts)

[2188  636 3399 3126 3123  380 2581 3239 3259 3088]


In [23]:
print("All total amounts:",amounts[:5])

All total amounts: [2188  636 3399 3126 3123]


In [24]:
orders_from_13 = orders_data[orders_data[:,1]==13] #Filter rows where restaurant_is==13
print(orders_from_13)

[[   4   13 3126]
 [   8   13 3239]
 [  10   13 3088]]


In [25]:
orders_data[3,2]=1500   #[row,column] 4th row,3th column change 3126->1500
print("Corrected 4th order:",orders_data[3])

Corrected 4th order: [   4   13 1500]


In [26]:
import pandas as pd

reviews_df = pd.read_csv("/content/DA314_S1_Reviews_Data_Concept.csv")
reviews_df

review_id user_id restaurant_id  order_date  rating  \
0      REV0001  USR002        RST007  01/04/2024     4.0   
1      REV0002  USR065        RST044  01/04/2024     3.6   
2      REV0003  USR080        RST058  01/04/2024     4.6   
3      REV0004  USR098        RST013  01/04/2024     5.0   
4      REV0005  USR147        RST030  01/04/2024     4.0   
...        ...     ...           ...         ...     ...   
1962   REV1963  USR034        RST078  31/03/2025     4.5   
1963   REV1964  USR058        RST024  31/03/2025     4.3   
1964   REV1965  USR080        RST033  31/03/2025     4.0   
1965   REV1966  USR165        RST061  31/03/2025     3.9   
1966   REV1967  USR199        RST055  31/03/2025     4.9   

                            review_text  
0              Satisfactory experience.  
1               Could have been better.  
2       Fantastic ambiance and quality.  
3       Fantastic ambiance and quality.  
4                 Neither good nor bad.  
...                                 ...  
1962  Great service and delicious food.  
1963                 Five-star service!  
1964            Could have been better.  
1965            Could have been better.  
1966   Will definitely come back again.  

[1967 rows x 6 columns]

In [27]:
#create a series by extracting 'Rating' column and setting review_id as label
rating_series = pd.Series(reviews_df['rating'].values, index=reviews_df['restaurant_id'])
print(rating_series.head())
print(type(rating_series))

restaurant_id
RST007    4.0
RST044    3.6
RST058    4.6
RST013    5.0
RST030    4.0
dtype: float64
<class 'pandas.core.series.Series'>


In [28]:
#create a series by extracting 'review_text' column without lable
review_series = reviews_df['review_text']
print(review_series.head())
print(type(review_series))

0           Satisfactory experience.
1            Could have been better.
2    Fantastic ambiance and quality.
3    Fantastic ambiance and quality.
4              Neither good nor bad.
Name: review_text, dtype: object
<class 'pandas.core.series.Series'>


In [29]:
#create a series by extracting 'review_text' column without lable
review_series = reviews_df['review_text']
print(review_series.head())
print(type(review_series))

0           Satisfactory experience.
1            Could have been better.
2    Fantastic ambiance and quality.
3    Fantastic ambiance and quality.
4              Neither good nor bad.
Name: review_text, dtype: object
<class 'pandas.core.series.Series'>


In [30]:
#Subset using iloc (position)
fifth_review = review_series.iloc[4]
print(fifth_review)

Neither good nor bad.


In [31]:
#Analysis the series
print("\nAnalysis of the rating series\n")
print(f"Mean: {rating_series.mean().round(1)}")
print(f"Median: {rating_series.median()}")
print(f"Mode: {rating_series.mode()[0]}")
print(f"Min: {rating_series.min()}")
print(f"Max: {rating_series.max()}")


Analysis of the rating series

Mean: 4.3
Median: 4.3
Mode: 5.0
Min: 2.5
Max: 5.0


In [32]:
# Group by index (restaurant_id) and calculate average
average_ratings = rating_series.groupby(rating_series.index).mean()
average_ratings = average_ratings.round(1)
print("Average Rating By restaurant_id:")
print(rating_series.head())

Average Rating By restaurant_id:
restaurant_id
RST007    4.0
RST044    3.6
RST058    4.6
RST013    5.0
RST030    4.0
dtype: float64


In [33]:
#Convert series to a datafreme
restaurant_ratings_df = average_ratings.to_frame(name="avg_rating")
# Rest label into column
restaurants_reviews_df = restaurant_ratings_df.reset_index("restaurant_id")
print(restaurant_ratings_df.head())

               avg_rating
restaurant_id            
RST001                4.3
RST002                4.2
RST003                4.2
RST004                4.2
RST005                4.3


S4 2nd sprint

In [35]:
import pandas as pd

# Read user_df.csv
user_df = pd.read_csv("/content/DA314_S2_Users_Data_Concept.csv")
print("User DataFrame:")
print(user_df)
print("\n")

# Read order_df.csv
order_df = pd.read_csv("/content/DA314_S2_Orders_Data_Concept.csv")
print("Order DataFrame:")
print(order_df)

User DataFrame:
    user_id             name  gender       city
0    USR001      Adira Kumar  Female     Mumbai
1    USR002       Damini Lal  Female    Kolkata
2    USR003      Shalv Walia    Male  Bangalore
3    USR004    Divij Agarwal    Male      Delhi
4    USR005  Reyansh Chauhan    Male     Mumbai
..      ...              ...     ...        ...
245  USR246       Kavya Lata  Female  Bangalore
246  USR247      Kashvi Vyas    Male       Pune
247  USR248    Dhanuk Bhatia    Male      Delhi
248  USR249     Yashvi Krish  Female  Bangalore
249  USR250       Kanav Sama    Male  Bangalore

[250 rows x 4 columns]


Order DataFrame:
     order_id user_id restaurant_id  order_date  total_amount  \
0     ORD0001  USR002        RST007  01/04/2024          2188   
1     ORD0002  USR065        RST044  01/04/2024           636   
2     ORD0003  USR080        RST058  01/04/2024          3399   
3     ORD0004  USR098        RST013  01/04/2024          3126   
4     ORD0005  USR147        RST030  01/

In [36]:
df_merge = pd.merge(user_df,order_df, on='user_id',how='inner')
print(df_merge.head())

  user_id         name  gender    city order_id restaurant_id  order_date  \
0  USR001  Adira Kumar  Female  Mumbai  ORD0302        RST035  27/05/2024   
1  USR001  Adira Kumar  Female  Mumbai  ORD0810        RST011  27/08/2024   
2  USR001  Adira Kumar  Female  Mumbai  ORD0827        RST011  30/08/2024   
3  USR001  Adira Kumar  Female  Mumbai  ORD1315        RST044  30/11/2024   
4  USR001  Adira Kumar  Female  Mumbai  ORD1544        RST023  15/01/2025   

   total_amount                                  items_ordered payment_method  \
0          2222                  Chicken Biryani, Idli Sambhar    Credit Card   
1          3003      Paneer Butter Masala, Samosa, Masala Dosa           Cash   
2          1246  Hakka Noodles, Veg Pulao, Dal Makhani, Samosa         Wallet   
3          2406  Samosa, Chicken Curry, Veg Pulao, Dal Makhani         Wallet   
4          2511                      Fried Rice, Chicken Curry    Credit Card   

  order_status  
0    Completed  
1    Completed  

In [37]:
df_join = user_df.set_index('user_id').join(
    order_df.set_index('user_id'),how ='inner')
print(df_join.head())

                name  gender    city order_id restaurant_id  order_date  \
user_id                                                                   
USR001   Adira Kumar  Female  Mumbai  ORD0302        RST035  27/05/2024   
USR001   Adira Kumar  Female  Mumbai  ORD0810        RST011  27/08/2024   
USR001   Adira Kumar  Female  Mumbai  ORD0827        RST011  30/08/2024   
USR001   Adira Kumar  Female  Mumbai  ORD1315        RST044  30/11/2024   
USR001   Adira Kumar  Female  Mumbai  ORD1544        RST023  15/01/2025   

         total_amount                                  items_ordered  \
user_id                                                                
USR001           2222                  Chicken Biryani, Idli Sambhar   
USR001           3003      Paneer Butter Masala, Samosa, Masala Dosa   
USR001           1246  Hakka Noodles, Veg Pulao, Dal Makhani, Samosa   
USR001           2406  Samosa, Chicken Curry, Veg Pulao, Dal Makhani   
USR001           2511                     

In [38]:
inner_join_df = pd.merge(user_df,order_df, on='user_id',how='inner')
print(inner_join_df.shape)

(1971, 11)


In [39]:
left_join_df = pd.merge(user_df,order_df, on='user_id', how='left')
print(left_join_df.shape)

(1971, 11)


In [40]:
right_join_df = pd.merge(user_df,order_df, on='user_id', how='right')
print(right_join_df.shape)

(1971, 11)


In [41]:
outer_join_df =pd.merge(user_df,order_df, on='user_id',how='outer')
print(outer_join_df.shape)

(1971, 11)


In [42]:
import pandas as pd

# Read the restaurants file
restaurants_df = pd.read_csv("/content/DA314_S2_Restaurants_Data_Concept.csv")
print("Restaurants Data:")
print(restaurants_df.head())

Restaurants Data:
  restaurant_id                name       city cuisine_type  avg_cost_for_two  \
0        RST001      Spicy Bites #1  Hyderabad      Mexican               490   
1        RST002     Spicy Corner #2     Mumbai       Indian               322   
2        RST003      Tasty Grill #3       Pune      Mexican               784   
3        RST004       Tasty Dine #4       Pune  Continental               561   
4        RST005  Delight Kitchen #5      Delhi     Japanese               326   

   rating  
0     4.3  
1     3.1  
2     3.2  
3     3.0  
4     4.6  


In [43]:

# Read the reviews file
reviews_df = pd.read_csv("/content/DA314_S2_Reviews_Data_Concept.csv")
print("\nReviews Data:")
print(reviews_df.head())


Reviews Data:
  review_id user_id restaurant_id  order_date  rating  \
0   REV0001  USR002        RST007  01/04/2024     4.0   
1   REV0002  USR065        RST044  01/04/2024     3.6   
2   REV0003  USR080        RST058  01/04/2024     4.6   
3   REV0004  USR098        RST013  01/04/2024     5.0   
4   REV0005  USR147        RST030  01/04/2024     4.0   

                       review_text  
0         Satisfactory experience.  
1          Could have been better.  
2  Fantastic ambiance and quality.  
3  Fantastic ambiance and quality.  
4            Neither good nor bad.  


In [44]:
#Join user with Order
orders_users = pd.merge(order_df,user_df, on='user_id', how='left')
#Join with Restaurants
orders_full_df = pd.merge(orders_users, restaurants_df,
                          on='restaurant_id', how='left',
                          suffixes=('_user','_restaurant')
                          )
orders_full_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1971 entries, 0 to 1970
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   order_id          1971 non-null   object 
 1   user_id           1971 non-null   object 
 2   restaurant_id     1971 non-null   object 
 3   order_date        1971 non-null   object 
 4   total_amount      1971 non-null   int64  
 5   items_ordered     1971 non-null   object 
 6   payment_method    1971 non-null   object 
 7   order_status      1971 non-null   object 
 8   name_user         1971 non-null   object 
 9   gender            1971 non-null   object 
 10  city_user         1971 non-null   object 
 11  name_restaurant   1971 non-null   object 
 12  city_restaurant   1971 non-null   object 
 13  cuisine_type      1971 non-null   object 
 14  avg_cost_for_two  1971 non-null   int64  
 15  rating            1971 non-null   float64
dtypes: float64(1), int64(2), object(13)
memory

In [45]:
#Common column's of each table[orders_users, restaurants_df] ->Suffixes are added
orders_full_df[['name_user','name_restaurant']].head()

name_user      name_restaurant
0      Damini Lal    Fusion Flavors #7
1    Adira Shetty  Delight Kitchen #44
2       Ela Dubey      Magic Grill #58
3  Darshit Chahal    Delight Grill #13
4     Akarsh Date      Magic Grill #30

In [46]:
restaurants_reviews_df = pd.merge(
    restaurants_df,
    reviews_df,
    on='restaurant_id',
    how='right',
    suffixes=('_restaurant', '_review')
)
print(restaurants_reviews_df.head())

  restaurant_id                 name       city cuisine_type  \
0        RST007    Fusion Flavors #7    Kolkata      Italian   
1        RST044  Delight Kitchen #44     Mumbai     American   
2        RST058      Magic Grill #58    Kolkata     American   
3        RST013    Delight Grill #13  Ahmedabad     Japanese   
4        RST030      Magic Grill #30  Bangalore     American   

   avg_cost_for_two  rating_restaurant review_id user_id  order_date  \
0             260.0                3.1   REV0001  USR002  01/04/2024   
1            1008.0                3.9   REV0002  USR065  01/04/2024   
2             655.0                4.6   REV0003  USR080  01/04/2024   
3            1350.0                4.1   REV0004  USR098  01/04/2024   
4             516.0                3.7   REV0005  USR147  01/04/2024   

   rating_review                      review_text  
0            4.0         Satisfactory experience.  
1            3.6          Could have been better.  
2            4.6  Fantasti

In [47]:
restaurants_reviews_df.isnull().sum()

restaurant_id        533
name                 533
city                 533
cuisine_type         533
avg_cost_for_two     533
rating_restaurant    533
review_id              0
user_id              533
order_date           533
rating_review         11
review_text            0
dtype: int64

In [48]:
restaurants_reviews_df['rating_review'].fillna(
    restaurants_reviews_df['rating_review'].mean(),
    inplace=True
)

restaurants_reviews_df.isnull().sum()

/tmp/ipython-input-2557202464.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  restaurants_reviews_df['rating_review'].fillna(


restaurant_id        533
name                 533
city                 533
cuisine_type         533
avg_cost_for_two     533
rating_restaurant    533
review_id              0
user_id              533
order_date           533
rating_review          0
review_text            0
dtype: int64

In [49]:
# check shape
restaurants_reviews_df.shape

(2500, 11)

In [50]:
# drop rows where cuisine_type(Column(s)) is null value (NaN)
restaurants_reviews_df = restaurants_reviews_df.dropna(subset=['cuisine_type'])

In [51]:
# drop rows with at least one NaN values(DROPNA)
restaurants_reviews_df.dropna(inplace=True)

In [52]:
restaurants_reviews_df.isnull().sum()   # check missing values


restaurant_id        0
name                 0
city                 0
cuisine_type         0
avg_cost_for_two     0
rating_restaurant    0
review_id            0
user_id              0
order_date           0
rating_review        0
review_text          0
dtype: int64

In [53]:
restaurants_reviews_df.shape

(1967, 11)

In [54]:
orders_full_df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...  
1966    False
1967     True
1968    False
1969    False
1970    False
Length: 1971, dtype: bool

In [55]:
orders_full_df.duplicated(subset=['order_id','user_id'])

0       False
1       False
2       False
3       False
4       False
        ...  
1966    False
1967     True
1968     True
1969     True
1970     True
Length: 1971, dtype: bool

In [56]:
print(restaurants_reviews_df.head())

  restaurant_id                 name       city cuisine_type  \
0        RST007    Fusion Flavors #7    Kolkata      Italian   
1        RST044  Delight Kitchen #44     Mumbai     American   
2        RST058      Magic Grill #58    Kolkata     American   
3        RST013    Delight Grill #13  Ahmedabad     Japanese   
4        RST030      Magic Grill #30  Bangalore     American   

   avg_cost_for_two  rating_restaurant review_id user_id  order_date  \
0             260.0                3.1   REV0001  USR002  01/04/2024   
1            1008.0                3.9   REV0002  USR065  01/04/2024   
2             655.0                4.6   REV0003  USR080  01/04/2024   
3            1350.0                4.1   REV0004  USR098  01/04/2024   
4             516.0                3.7   REV0005  USR147  01/04/2024   

   rating_review                      review_text  
0            4.0         Satisfactory experience.  
1            3.6          Could have been better.  
2            4.6  Fantasti

In [57]:
orders_full_df.duplicated(subset=['order_id','user_id']).sum()

np.int64(4)

In [58]:
#Drop duplicated rows
clean_orders_1=orders_full_df.drop_duplicates()
clean_orders_1.duplicated().sum()

np.int64(0)

In [59]:
#Dropped duplicates based on specific('order_id' and 'user_id') keep's first and drop other duplicates in this case.
clean_orders_2=orders_full_df.drop_duplicates(subset=['order_id','user_id'],keep='first')
clean_orders_2.duplicated(subset=['order_id','user_id']).sum()

np.int64(0)

In [60]:
latest_orders=orders_full_df.sort_values('order_date').drop_duplicates(subset=['user_id'],keep='last')
latest_orders.duplicated(subset=['user_id']).sum()

np.int64(0)